// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChItLkbZ9t-BdJTwDmjdlGh3WkciDqET0',
    appId: '1:531471190184:web:0a3f56bd02ee02ce001a9d',
    messagingSenderId: '531471190184',
    projectId: 'ambulanceapp-6667d',
    authDomain: 'ambulanceapp-6667d.firebaseapp.com',
    databaseURL: 'https://ambulanceapp-6667d-default-rtdb.firebaseio.com',
    storageBucket: 'ambulanceapp-6667d.appspot.com',
    measurementId: 'G-TQ763495P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGAbhuMB9ppxEH4gvm_C6etMDhsOLWxc0',
    appId: '1:531471190184:android:b02dd854cc5e65f8001a9d',
    messagingSenderId: '531471190184',
    projectId: 'ambulanceapp-6667d',
    databaseURL: 'https://ambulanceapp-6667d-default-rtdb.firebaseio.com',
    storageBucket: 'ambulanceapp-6667d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0fXzKLuYLPLdAfx6I9TUkORiK1B-kpas',
    appId: '1:531471190184:ios:92fd22d9423855d9001a9d',
    messagingSenderId: '531471190184',
    projectId: 'ambulanceapp-6667d',
    databaseURL: 'https://ambulanceapp-6667d-default-rtdb.firebaseio.com',
    storageBucket: 'ambulanceapp-6667d.appspot.com',
    iosClientId: '531471190184-f8c05fffg6gocgv7amqfvr4cdrpvee4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0fXzKLuYLPLdAfx6I9TUkORiK1B-kpas',
    appId: '1:531471190184:ios:92fd22d9423855d9001a9d',
    messagingSenderId: '531471190184',
    projectId: 'ambulanceapp-6667d',
    databaseURL: 'https://ambulanceapp-6667d-default-rtdb.firebaseio.com',
    storageBucket: 'ambulanceapp-6667d.appspot.com',
    iosClientId: '531471190184-f8c05fffg6gocgv7amqfvr4cdrpvee4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambApp',
  );
}
